---
mountOptions:
  default: defaults
  btrfs:   defaults,noatime,compress=zstd
  tmpfs:   defaults,nodev,nosuid
efiMountOptions: "umask=0077"

# Write individual fstab entries for each btrfs subvolume
btrfsSubvolumes:
  - mountPoint: /
    subvolume: /@
  - mountPoint: /home
    subvolume: /@home
  - mountPoint: /var/log
    subvolume: /@log
  - mountPoint: /var/cache/pacman/pkg
    subvolume: /@pkg
