---
extraMounts:
  - device: proc
    fs:     proc
    mountPoint: /proc
  - device: sys
    fs:     sysfs
    mountPoint: /sys
  - device: efivarfs
    fs:     efivarfs
    mountPoint: /sys/firmware/efi/efivars
  - device: /dev
    fs:     devtmpfs
    mountPoint: /dev
    options: bind
  - device: /dev/pts
    fs:     devpts
    mountPoint: /dev/pts
    options: gid=5,mode=620
  - device: /dev/shm
    fs:     tmpfs
    mountPoint: /dev/shm
  - device: /run/archiso/bootmnt
    fs:     none
    mountPoint: /run/archiso/bootmnt
    options: bind

extraMountsEfi:
  - device: efivarfs
    fs:     efivarfs
    mountPoint: /sys/firmware/efi/efivars
