---
backend:   pacman
update_db: false

operations:
  - remove:
    - calamares
    - calamares-libs
    - arch-install-scripts
    - archinstall
    - b43-fwcutter
    - broadcom-wl
    - clonezilla
    - cloud-init
    - darkhttpd
    - ddrescue
    - espeakup
    - fsarchiver
    - gpart
    - gpm
    - hyperv
    - irssi
    - livecd-sounds
    - lynx
    - mc
    - memtest86+
    - memtest86+-efi
    - mkinitcpio-archiso
    - mkinitcpio-nfs-utils
    - nbd
    - open-iscsi
    - open-vm-tools
    - partclone
    - partimage
    - pptpclient
    - qemu-guest-agent
    - refind
    - rp-pppoe
    - screen
    - squashfs-tools
    - syslinux
    - testdisk
    - tmux
    - virtualbox-guest-utils-nox
    - vpnc
    - wvdial
    - xl2tpd
    - brltty
    - bolt
    - reflector
    - ckbcomp
    - hwinfo
    - os-prober
    - python-pyqt5
    - python-yaml
    - python-jsonschema
    - qt5-webengine
