---
efiSystemPartition:         "/boot/efi"
efiSystemPartitionSize:     "512 MiB"
efiSystemPartitionName:     "EFI"
initialPartitioningChoice:  best
initialSwapChoice:          small
defaultFileSystemType:      "ext4"
availableFileSystemTypes:   ["ext4", "btrfs", "xfs", "f2fs"]
allowManualPartitioning:    true
showNotEncryptedBootMessage: true
