---
services:
  - name: NetworkManager
    mandatory: true
  - name: gdm
    mandatory: false
  - name: bluetooth
    mandatory: false
  - name: cups
    mandatory: false
  - name: firewalld
    mandatory: false
  - name: fwupd
    mandatory: false
  - name: power-profiles-daemon
    mandatory: false

targets: []

disable:
  - name: pacman-init
    mandatory: false
  - name: choose-mirror
    mandatory: false
  - name: reflector
    mandatory: false
  - name: livecd-alsa-unmuter
    mandatory: false
  - name: livecd-talk
    mandatory: false
  - name: iwd
    mandatory: false
  - name: sshd
    mandatory: false
  - name: systemd-networkd
    mandatory: false
