---
# The squashfs image is at /run/archiso/bootmnt/<install_dir>/<arch>/airootfs.sfs
# profiledef.sh: install_dir="arch", arch="x86_64"
unpack:
  - source:      "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
    sourcefs:    "squashfs"
    destination: ""
